version: '3.8'
services:
  mysql:
    image: mysql:8.3
    platform: linux/arm64/v8
    command: "mysqld --character-set-server=utf8mb4"
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - "3319:3306"
  redis-cluster:
    image: grokzen/redis-cluster:7.0.10
    platform: linux/amd64
    environment:
      IP: '127.0.0.1'
      INITIAL_PORT: 8000
    ports:
      - '8000-8005:8000-8005'
  mongo:
    image: mongo:5.0.22
    platform: linux/arm64/v8
    container_name: mongodb
    ports:
      - "27018:27017"