version: '3.8'
services:
  mysql:
    image: mysql:8.4.3
    platform: linux/arm64/v8
    command: "mysqld --character-set-server=utf8mb4"
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - "4202:3306"
  redis-cluster:
    image: grokzen/redis-cluster:7.2.5
    platform: linux/amd64
    environment:
      IP: '127.0.0.1'
      INITIAL_PORT: 4211
    ports:
      - '4211-4213:8001-8003'
  mongo:
    image: mongo:7.0.16
    platform: linux/arm64/v8
    ports:
      - "4201:27017"