version: '3.3'
services:
  maria:
    image: mariadb:10.7.1
    platform: linux/arm64/v8
    container_name: mariadb
    command: "mysqld --character-set-server=utf8mb4"
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: smooth-coated-otter
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - "3319:3306"
  redis:
    image: redis:6.2.6
    platform: linux/arm64/v8
    network_mode: "host"
    container_name: redis-cluster
    environment:
      - REQUIREPASS=local
    ports:
      - "6381:6379"
  mongo:
    image: mongo:5.0.5
    platform: linux/arm64/v8
    container_name: mongodb
    ports:
      - "27018:27017"